import dotenv from "dotenv";
dotenv.config();

const {
  PORT,
  MONGO_URI,
  NODEMAILER_PASSKEY,
  SENDER_EMAIL,
  CLIENT_URL,
  SERVER_URL,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASS,
} = process.env;

export {
  PORT,
  MONGO_URI,
  NODEMAILER_PASSKEY,
  SENDER_EMAIL,
  CLIENT_URL,
  SERVER_URL,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASS,
};
